### ISSUE TITLE
Unable to generate the data

### ISSUE THREAD

**Issue by noman-maken** [humhub-contrib/profiler#1]
Hi, unable to generate the data, the error is

![image](https://user-images.githubusercontent.com/60031819/209903610-90210b6a-3b34-4b50-9ba2-058e6e94f8fa.png)

**Comment by ArchBlood** [comment]
Did you make sure that you ran `composer update` then enable the module from the Module section?

**Comment by ArchBlood** [comment]
@luke- maybe change the title here as I did find that there is a bug when you load the generated content;

```log
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tags' in 'field list'
```
After this all content after the load command returns a `NULL` and overwrites all entries including pre-generated admin user.

**Comment by noman-maken** [comment]
@ArchBlood Yes I have run the composer and after that put files in `protected ==> Modules` and enable the module from the module section and then run and the command for generating the data

**Comment by ArchBlood** [comment]
> @ArchBlood Yes I have run the composer and after that put files in `protected ==> Modules` and enable the module from the module section and then run and the command for generating the data

Your issue should be fixed by #2

**Comment by ArchBlood** [comment]
Personally I was able to get the module running with no issues other than the one I reported :thinking:

**Comment by noman-maken** [comment]
@ArchBlood @luke- 
I'm still facing the issue, however I again install humhub and also update the profiler module

![image](https://user-images.githubusercontent.com/60031819/211360979-ee2a6e1b-7ebd-4039-be3a-33498fbe7949.png)

**Comment by ArchBlood** [comment]
> @ArchBlood @luke- 
> I'm still facing the issue, however I again install humhub and also update the profiler module
> 
> ![image](https://user-images.githubusercontent.com/60031819/211360979-ee2a6e1b-7ebd-4039-be3a-33498fbe7949.png)
> 

Could you provide which PHP version you're using?

**Comment by noman-maken** [comment]
@ArchBlood PHP - Version - 8.1.6

**Comment by ArchBlood** [comment]
> @ArchBlood PHP - Version - 8.1.6

I've currently tested with _**PHP 8.1.13**_ with no problems generating data see the screenshots;

![Screenshot_1](https://user-images.githubusercontent.com/35392110/211367231-68fdf99d-1f91-4fab-a490-d7ecb0cf629f.png)
![Screenshot_2](https://user-images.githubusercontent.com/35392110/211367236-bf42a909-91c3-4716-8edf-f33971bae964.png)
![Screenshot_3](https://user-images.githubusercontent.com/35392110/211367239-d4034e35-1761-458a-9789-ca31e5a609f0.png)
![Screenshot_4](https://user-images.githubusercontent.com/35392110/211367460-ed43ac0f-f931-45a0-b6c1-681aa8695855.png)

The issue is loading command `php yii profiler/fixture/load "*"` does not work apparently, I'll look into this.

**Comment by ArchBlood** [comment]
Maybe something to do with the following for you;
https://github.com/humhub-contrib/profiler/blob/d997bce3f302aa6874e1a2549e1dd3d33f49b9b2/faker/ContentContainerProvider.php#L20

Maybe change to the following?
```php
'guid' => (new \ReflectionClass($class))->getShortName() . '::' . static::$index,
```

**Comment by noman-maken** [comment]
Same issue

**Comment by noman-maken** [comment]
> Maybe something to do with the following for you;
> 
> https://github.com/humhub-contrib/profiler/blob/d997bce3f302aa6874e1a2549e1dd3d33f49b9b2/faker/ContentContainerProvider.php#L20
> 
> Maybe change to the following?
> 
> ```
> 'guid' => (new \ReflectionClass($class))->getShortName() . '::' . static::$index,
> ```

You have just added the two spaces in line 20 🤔🤔🤔
